# Generated by Django 5.2.7 on 2025-10-10 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyIntegrationDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sync Dashboard', max_length=100)),
            ],
            options={
                'verbose_name': 'Sync Dashboard',
                'verbose_name_plural': 'Sync Dashboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopifyStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_domain', models.CharField(help_text='e.g., 7fa66c-ac.myshopify.com', max_length=100, unique=True)),
                ('store_name', models.CharField(help_text='Business name', max_length=100)),
                ('api_key', models.CharField(max_length=100)),
                ('api_secret', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=100)),
                ('api_version', models.CharField(default='2025-01', max_length=20)),
                ('currency', models.CharField(default='AUD', max_length=10)),
                ('timezone', models.CharField(default='Australia/Sydney', max_length=50)),
                ('country_code', models.CharField(default='AU', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['store_name'],
            },
        ),
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('customers_sync', 'Customers Sync'), ('products_sync', 'Products Sync'), ('orders_sync', 'Orders Sync'), ('inventory_sync', 'Inventory Sync'), ('shipping_sync', 'Shipping Sync'), ('full_sync', 'Full Sync')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('processed_records', models.IntegerField(default=0)),
                ('created_records', models.IntegerField(default=0)),
                ('updated_records', models.IntegerField(default=0)),
                ('error_records', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_operations', to='shopify_integration.shopifystore')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_type', models.CharField(choices=[('rest', 'REST API'), ('graphql', 'GraphQL API')], max_length=20)),
                ('current_calls', models.IntegerField(default=0)),
                ('max_calls', models.IntegerField(default=40)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('is_throttled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to='shopify_integration.shopifystore')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('store', 'api_type')},
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(help_text='Shopify Webhook ID', max_length=100, unique=True)),
                ('topic', models.CharField(help_text='e.g., orders/create, customers/update', max_length=100)),
                ('address', models.URLField(help_text='Webhook endpoint URL')),
                ('format', models.CharField(choices=[('json', 'JSON'), ('xml', 'XML')], default='json', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='shopify_integration.shopifystore')),
            ],
            options={
                'ordering': ['topic'],
                'unique_together': {('store', 'topic')},
            },
        ),
    ]
