# Generated by Django 5.2.7 on 2025-10-10 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('bulk_import', 'Bulk Import'), ('single_update', 'Single Update'), ('webhook_update', 'Webhook Update')], max_length=20)),
                ('carriers_processed', models.IntegerField(default=0)),
                ('profiles_processed', models.IntegerField(default=0)),
                ('zones_processed', models.IntegerField(default=0)),
                ('methods_processed', models.IntegerField(default=0)),
                ('fulfillment_orders_processed', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopifyCarrierService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(help_text='Shopify Carrier Service ID', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('service_discovery', models.BooleanField(default=False)),
                ('carrier_service_type', models.CharField(choices=[('api', 'API'), ('legacy', 'Legacy')], max_length=20)),
                ('callback_url', models.URLField(blank=True, help_text='Callback URL for rate calculations')),
                ('format', models.CharField(choices=[('json', 'JSON'), ('xml', 'XML')], default='json', max_length=10)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['shopify_id'], name='shipping_sh_shopify_58860d_idx'), models.Index(fields=['active'], name='shipping_sh_active_1823b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopifyDeliveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(help_text='Shopify Delivery Profile ID', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=False)),
                ('locations_without_rates_to_ship', models.JSONField(blank=True, default=list)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['shopify_id'], name='shipping_sh_shopify_519db7_idx'), models.Index(fields=['active'], name='shipping_sh_active_ce3b95_idx'), models.Index(fields=['default'], name='shipping_sh_default_6461cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopifyDeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(help_text='Shopify Delivery Zone ID', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('countries', models.JSONField(default=list, help_text='List of country codes')),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='shipping.shopifydeliveryprofile')),
            ],
            options={
                'ordering': ['profile', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShopifyDeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(help_text='Shopify Delivery Method ID', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('method_type', models.CharField(choices=[('shipping', 'Shipping'), ('pickup', 'Pickup')], max_length=20)),
                ('min_delivery_date_time', models.DateTimeField(blank=True, null=True)),
                ('max_delivery_date_time', models.DateTimeField(blank=True, null=True)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='shipping.shopifydeliveryzone')),
            ],
            options={
                'ordering': ['zone', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShopifyFulfillmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(help_text='Shopify Fulfillment Order ID', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled'), ('incomplete', 'Incomplete'), ('closed', 'Closed')], max_length=20)),
                ('request_status', models.CharField(choices=[('unsubmitted', 'Unsubmitted'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancellation_requested', 'Cancellation Requested'), ('cancellation_accepted', 'Cancellation Accepted'), ('closed', 'Closed')], max_length=30)),
                ('fulfill_at', models.DateTimeField(blank=True, null=True)),
                ('fulfill_by', models.DateTimeField(blank=True, null=True)),
                ('international_duties', models.JSONField(blank=True, null=True)),
                ('delivery_method', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.shopifylocation')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_orders', to='orders.shopifyorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopifyFulfillmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(help_text='Shopify Fulfillment Service ID', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('handle', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('service_name', models.CharField(blank=True, max_length=255)),
                ('include_pending_stock', models.BooleanField(default=False)),
                ('requires_shipping_method', models.BooleanField(default=False)),
                ('tracking_support', models.BooleanField(default=False)),
                ('callback_url', models.URLField(blank=True)),
                ('format', models.CharField(choices=[('json', 'JSON'), ('xml', 'XML')], default='json', max_length=10)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['shopify_id'], name='shipping_sh_shopify_a84970_idx'), models.Index(fields=['handle'], name='shipping_sh_handle_fb992e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='shopifydeliveryzone',
            index=models.Index(fields=['shopify_id'], name='shipping_sh_shopify_8a1c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifydeliveryzone',
            index=models.Index(fields=['profile'], name='shipping_sh_profile_e29067_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifydeliverymethod',
            index=models.Index(fields=['shopify_id'], name='shipping_sh_shopify_334825_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifydeliverymethod',
            index=models.Index(fields=['zone'], name='shipping_sh_zone_id_c0f9a8_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifydeliverymethod',
            index=models.Index(fields=['method_type'], name='shipping_sh_method__0b6695_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyfulfillmentorder',
            index=models.Index(fields=['shopify_id'], name='shipping_sh_shopify_dad1fe_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyfulfillmentorder',
            index=models.Index(fields=['order'], name='shipping_sh_order_i_1d7cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyfulfillmentorder',
            index=models.Index(fields=['status'], name='shipping_sh_status_711d00_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyfulfillmentorder',
            index=models.Index(fields=['location'], name='shipping_sh_locatio_09566b_idx'),
        ),
    ]
