# Generated by Django 4.2.23 on 2025-11-30 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(help_text='Unique identifier for this rate', max_length=255)),
                ('title', models.CharField(help_text='Display name of the shipping rate', max_length=255)),
                ('price_amount', models.DecimalField(decimal_places=2, help_text='Rate price amount', max_digits=10)),
                ('price_currency', models.CharField(default='USD', help_text='Currency code (USD, CAD, etc.)', max_length=3)),
                ('description', models.TextField(blank=True, help_text='Service description')),
                ('service_code', models.CharField(blank=True, help_text='Service code (STANDARD, EXPRESS, etc.)', max_length=100)),
                ('min_delivery_days', models.IntegerField(blank=True, help_text='Minimum delivery days', null=True)),
                ('max_delivery_days', models.IntegerField(blank=True, help_text='Maximum delivery days', null=True)),
                ('origin_country', models.CharField(blank=True, help_text='Origin country code', max_length=2)),
                ('destination_country', models.CharField(blank=True, help_text='Destination country code', max_length=2)),
                ('destination_zone', models.CharField(blank=True, help_text='Destination zone name', max_length=255)),
                ('phone_required', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
                ('sample_weight_grams', models.IntegerField(blank=True, help_text='Sample package weight', null=True)),
                ('sample_value_cents', models.IntegerField(blank=True, help_text='Sample package value', null=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shopifycarrierservice')),
                ('delivery_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shopifydeliverymethod')),
            ],
            options={
                'verbose_name': 'Shipping Rate',
                'verbose_name_plural': 'Shipping Rates',
                'ordering': ['destination_country', 'price_amount'],
                'indexes': [models.Index(fields=['carrier'], name='shipping_sh_carrier_f6c419_idx'), models.Index(fields=['delivery_method'], name='shipping_sh_deliver_87f7ba_idx'), models.Index(fields=['destination_country'], name='shipping_sh_destina_2a8b58_idx'), models.Index(fields=['active'], name='shipping_sh_active_892c04_idx'), models.Index(fields=['handle'], name='shipping_sh_handle_e5f005_idx')],
            },
        ),
    ]
