# Generated by Django 4.2.23 on 2025-11-30 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_shippingrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentTrackingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, help_text='The name of the tracking company (e.g., FedEx, UPS, USPS, DHL)', max_length=255)),
                ('number', models.CharField(blank=True, help_text='The tracking number provided by the shipping carrier', max_length=255)),
                ('url', models.URLField(blank=True, help_text="The URL to track the fulfillment on the carrier's website", max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tracking info is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
                ('fulfillment_order', models.ForeignKey(help_text='The fulfillment order this tracking info belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tracking_info', to='shipping.shopifyfulfillmentorder')),
            ],
            options={
                'verbose_name': 'Fulfillment Tracking Info',
                'verbose_name_plural': 'Fulfillment Tracking Info',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fulfillment_order'], name='shipping_fu_fulfill_2c6dc1_idx'), models.Index(fields=['company'], name='shipping_fu_company_643883_idx'), models.Index(fields=['number'], name='shipping_fu_number_07e067_idx'), models.Index(fields=['is_active'], name='shipping_fu_is_acti_abc5b5_idx')],
            },
        ),
    ]
