# Generated by Django 4.2.23 on 2025-12-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_fulfillmenttrackinginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyfulfillmentorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shopifyfulfillmentorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
