# Generated by Django 4.2.23 on 2025-11-29 14:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0002_shopifyproduct_created_in_django_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(blank=True, help_text='Shopify SubscriptionContract GID', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed')], default='ACTIVE', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('next_billing_date', models.DateField(blank=True, help_text='Next billing date', null=True)),
                ('billing_policy_interval', models.CharField(default='MONTH', max_length=10)),
                ('billing_policy_interval_count', models.IntegerField(default=1)),
                ('next_delivery_date', models.DateField(blank=True, help_text='Next delivery date', null=True)),
                ('delivery_policy_interval', models.CharField(default='MONTH', max_length=10)),
                ('delivery_policy_interval_count', models.IntegerField(default=1)),
                ('line_items', models.JSONField(default=list, help_text='Subscription line items (products)')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_address', models.JSONField(blank=True, default=dict, help_text='Delivery address details')),
                ('payment_method_id', models.CharField(blank=True, help_text='Shopify payment method ID', max_length=255)),
                ('contract_created_at', models.DateTimeField(blank=True, help_text='When subscription was created in Shopify', null=True)),
                ('contract_updated_at', models.DateTimeField(blank=True, help_text='Last update in Shopify', null=True)),
                ('trial_end_date', models.DateField(blank=True, help_text='Trial period end date', null=True)),
                ('billing_cycle_count', models.IntegerField(default=0, help_text='Number of billing cycles completed')),
                ('total_cycles', models.IntegerField(blank=True, help_text='Total cycles (null = infinite)', null=True)),
                ('created_in_django', models.BooleanField(default=False, help_text='True if created in Django')),
                ('needs_shopify_push', models.BooleanField(default=False, help_text='True if needs push to Shopify')),
                ('shopify_push_error', models.TextField(blank=True, help_text='Last push error')),
                ('last_pushed_to_shopify', models.DateTimeField(blank=True, null=True)),
                ('last_synced_from_shopify', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer who owns this subscription', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='customers.shopifycustomer')),
            ],
            options={
                'verbose_name': 'Customer Subscription',
                'verbose_name_plural': 'Customer Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('import_from_shopify', 'Import from Shopify'), ('push_to_shopify', 'Push to Shopify'), ('update_in_shopify', 'Update in Shopify'), ('cancel_in_shopify', 'Cancel in Shopify'), ('bulk_sync', 'Bulk Sync')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('subscriptions_processed', models.IntegerField(default=0)),
                ('subscriptions_successful', models.IntegerField(default=0)),
                ('subscriptions_failed', models.IntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=255)),
            ],
            options={
                'verbose_name': 'Subscription Sync Log',
                'verbose_name_plural': 'Subscription Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionBillingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('shopify_order_id', models.CharField(blank=True, help_text='Created order GID if successful', max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_attempts', to='customer_subscriptions.customersubscription')),
            ],
            options={
                'verbose_name': 'Billing Attempt',
                'verbose_name_plural': 'Billing Attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='SellingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(blank=True, help_text='Shopify SellingPlan GID', max_length=255, null=True, unique=True)),
                ('shopify_selling_plan_group_id', models.CharField(blank=True, help_text='Parent SellingPlanGroup GID', max_length=255)),
                ('name', models.CharField(help_text="Plan name (e.g., 'Monthly Box')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Plan description')),
                ('billing_policy', models.CharField(choices=[('RECURRING', 'Recurring'), ('ON_PURCHASE', 'On Purchase')], default='RECURRING', max_length=20)),
                ('billing_interval', models.CharField(choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'), ('YEAR', 'Year')], default='MONTH', max_length=10)),
                ('billing_interval_count', models.IntegerField(default=1, help_text='e.g., 1 for monthly, 3 for quarterly', validators=[django.core.validators.MinValueValidator(1)])),
                ('billing_anchors', models.JSONField(blank=True, default=list, help_text='Billing anchor days')),
                ('price_adjustment_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount'), ('FIXED_AMOUNT', 'Fixed Amount Discount'), ('PRICE', 'Fixed Price')], default='PERCENTAGE', max_length=20)),
                ('price_adjustment_value', models.DecimalField(decimal_places=2, default=0, help_text='Discount/price value', max_digits=10)),
                ('delivery_policy', models.CharField(choices=[('RECURRING', 'Recurring'), ('ON_PURCHASE', 'On Purchase')], default='RECURRING', max_length=20)),
                ('delivery_interval', models.CharField(choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'), ('YEAR', 'Year')], default='MONTH', max_length=10)),
                ('delivery_interval_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('delivery_anchors', models.JSONField(blank=True, default=list, help_text='Delivery anchor days')),
                ('fulfillment_exact_time', models.BooleanField(default=False, help_text='Fulfill at exact time')),
                ('fulfillment_intent', models.CharField(choices=[('FULFILLMENT_BEGIN', 'Fulfillment Begin'), ('FULFILLMENT_EXACT_TIME', 'Fulfillment Exact Time')], default='FULFILLMENT_BEGIN', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_in_django', models.BooleanField(default=False, help_text='True if created in Django (not imported)')),
                ('needs_shopify_push', models.BooleanField(default=False, help_text='True if needs push to Shopify')),
                ('shopify_push_error', models.TextField(blank=True, help_text='Last push error message')),
                ('last_pushed_to_shopify', models.DateTimeField(blank=True, null=True)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, related_name='selling_plans', to='products.shopifyproduct')),
            ],
            options={
                'verbose_name': 'Selling Plan',
                'verbose_name_plural': 'Selling Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='selling_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_subscriptions', to='customer_subscriptions.sellingplan'),
        ),
        migrations.AddIndex(
            model_name='sellingplan',
            index=models.Index(fields=['shopify_id'], name='customer_su_shopify_f6389a_idx'),
        ),
        migrations.AddIndex(
            model_name='sellingplan',
            index=models.Index(fields=['is_active'], name='customer_su_is_acti_187cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='sellingplan',
            index=models.Index(fields=['needs_shopify_push'], name='customer_su_needs_s_40d7d6_idx'),
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['shopify_id'], name='customer_su_shopify_16c349_idx'),
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['customer', 'status'], name='customer_su_custome_900f37_idx'),
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['status'], name='customer_su_status_f2163f_idx'),
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['next_billing_date'], name='customer_su_next_bi_8492d1_idx'),
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['needs_shopify_push'], name='customer_su_needs_s_3d0614_idx'),
        ),
    ]
