# Generated by Django 4.2.23 on 2025-11-29 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_shopifyorderaddress_province'),
        ('customers', '0001_initial'),
        ('products', '0002_shopifyproduct_created_in_django_and_more'),
        ('customer_subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(default='Australia', max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_validated', models.BooleanField(default=False, help_text='Address validated by shipping carrier')),
                ('validation_notes', models.TextField(blank=True, help_text='Address validation notes or corrections')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, help_text='Who updated the address', max_length=100)),
                ('needs_shopify_sync', models.BooleanField(default=True, help_text='Address needs sync to Shopify subscriptions')),
                ('last_shopify_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_address', to='customers.shopifycustomer')),
            ],
            options={
                'verbose_name': 'Subscription Address',
                'verbose_name_plural': 'Subscription Addresses',
            },
        ),
        migrations.CreateModel(
            name='ShippingCutoffLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('REMINDER', 'Cutoff Reminder'), ('CUTOFF', 'Cutoff Notification'), ('SHIPPED', 'Shipping Confirmation')], max_length=20)),
                ('cutoff_date', models.DateField(help_text='The cutoff date for this notification')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoff_notifications', to='customers.shopifycustomer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoff_logs', to='orders.shopifyorder')),
            ],
            options={
                'verbose_name': 'Shipping Cutoff Log',
                'verbose_name_plural': 'Shipping Cutoff Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductShippingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_days', models.IntegerField(default=7, help_text='Days before shipping when orders are cut off')),
                ('reminder_days', models.IntegerField(default=14, help_text='Days before cutoff to send reminder (default: 14)')),
                ('processing_days', models.IntegerField(default=2, help_text='Days needed to process/prepare order')),
                ('estimated_transit_days', models.IntegerField(default=5, help_text='Estimated shipping transit time')),
                ('special_handling', models.BooleanField(default=False, help_text='Requires special handling')),
                ('handling_notes', models.TextField(blank=True, help_text='Special handling instructions')),
                ('international_shipping', models.BooleanField(default=True, help_text='Available for international shipping')),
                ('restricted_countries', models.JSONField(blank=True, default=list, help_text='Country codes where shipping is restricted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_config', to='products.shopifyproduct')),
            ],
            options={
                'verbose_name': 'Product Shipping Config',
                'verbose_name_plural': 'Product Shipping Configs',
            },
        ),
        migrations.CreateModel(
            name='OrderAddressOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(default='Australia', max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('reason', models.CharField(blank=True, help_text='Reason for address override', max_length=255)),
                ('is_temporary', models.BooleanField(default=True, help_text='True for one-time override, False for permanent change')),
                ('created_by', models.CharField(help_text='Who created this override', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('needs_shopify_sync', models.BooleanField(default=True)),
                ('last_shopify_sync', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_override', to='orders.shopifyorder')),
            ],
            options={
                'verbose_name': 'Order Address Override',
                'verbose_name_plural': 'Order Address Overrides',
            },
        ),
    ]
