# Generated by Django 4.2.23 on 2025-11-30 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_subscriptions', '0008_subscription_engine_v3_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersubscription',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='customersubscription',
            name='cancellation_survey_data',
        ),
        migrations.RemoveField(
            model_name='customersubscription',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='customersubscription',
            name='renewal_schedule_months',
        ),
        migrations.RemoveField(
            model_name='sellingplan',
            name='current_spots_taken',
        ),
        migrations.RemoveField(
            model_name='sellingplan',
            name='max_spots',
        ),
        migrations.RemoveField(
            model_name='sellingplan',
            name='unique_signup_link',
        ),
        migrations.RemoveField(
            model_name='sellingplan',
            name='waitlist_enabled',
        ),
        migrations.RemoveField(
            model_name='sellingplan',
            name='waitlist_password',
        ),
        migrations.DeleteModel(
            name='SubscriptionWaitlist',
        ),
    ]
