# Generated by Django 4.2.23 on 2025-12-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_subscriptions', '0009_remove_customersubscription_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingplan',
            name='shopify_selling_plan_group_id',
            field=models.CharField(blank=True, help_text='Parent SellingPlanGroup GID', max_length=255, null=True),
        ),
    ]
