"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the repository root
env_path = BASE_DIR.parent.parent / '.env'
load_dotenv(dotenv_path=env_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g!@oi#!t-u06qml(#6jm6=b!f-=f^%i6yb@nc+xrf%^2o0fei6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'lavish-backend.endevops.net',
    'https://lavish-backend.endevops.net',
    'viewing.endevops.net',
    '.myshopify.com',  # Allow all Shopify store domains
]

# CSRF Trusted Origins
CSRF_TRUSTED_ORIGINS = [
    'https://lavish-backend.endevops.net',
    'https://viewing.endevops.net',
    'http://localhost:8003',
    'http://127.0.0.1:8003',
]


# ============================================================================
# EMAIL CONFIGURATION
# ============================================================================

# Use console backend for development (prints emails to console)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production with SMTP, use these settings instead:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
# EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
# EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
# EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
# EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
# DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@lavish.com')


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Must be before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'crispy_forms',
    'import_export',
    
    # Custom apps
    'api',
    'accounts',
    'customers',
    'products',
    'orders',
    'inventory',
    'shipping',
    'payments',
    'shopify_integration',
    'locations',
    'skips',
    'customer_subscriptions',
    'email_manager',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # Disabled for API development
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'locations.shopify_currency_service.LocaleMiddleware',  # Currency and locale detection
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'locations.context_processors.currency_context',  # Currency context for templates
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'lavish_library.db',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Australia/Sydney'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# JAZZMIN CONFIGURATION - Lavish Library Admin Theme
# ============================================================================

JAZZMIN_SETTINGS = {
    # Site branding
    "site_title": "Lavish Library Admin",
    "site_header": "Lavish Library",
    "site_brand": "Lavish Library",
    "site_logo": "img/lavish-logo.png",
    "login_logo": "img/lavish-logo.png",
    "login_logo_dark": "img/lavish-logo.png",
    "site_logo_classes": "lavish-logo",
    "site_icon": "img/lavish-logo.png",
    "welcome_sign": "Welcome to Lavish Library Admin",
    "copyright": "Lavish Library",
    "search_model": ["accounts.CustomUser", "customers.ShopifyCustomer", "orders.ShopifyOrder", "products.ShopifyProduct"],
    
    # User menu
    "user_avatar": None,
    
    # Top Menu
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["accounts.view_customuser"]},
        {"name": "View Site", "url": "https://7fa66c-ac.myshopify.com/", "new_window": True},
        {"name": "Support", "url": "https://github.com/eo-nwanze/lavish/issues", "new_window": True},
        {"model": "accounts.CustomUser"},
    ],
    
    # User menu (dropdown)
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/eo-nwanze/lavish/issues", "icon": "fas fa-life-ring", "new_window": True},
        {"model": "accounts.CustomUser"}
    ],
    
    # Side Menu
    "show_sidebar": True,
    "navigation_expanded": False,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "auth",
        "customers",
        "customer_subscriptions",
        "orders",
        "skips",
        "products",
        "inventory",
        "shipping",
        "payments",
        "email_manager",
        "locations",
        "shopify_integration",
    ],
    
    # Icons for models and apps - Font Awesome (use lowercase model names)el names)
    "icons": {
        # App-level icons (these appear in sidebar for parent items)
        "auth": "fas fa-users-cog",
        "customers": "fas fa-user",
        "customer_subscriptions": "fas fa-sync-alt",
        "orders": "fas fa-shopping-cart",
        "skips": "fas fa-forward",
        "products": "fas fa-box",
        "inventory": "fas fa-boxes",
        "shipping": "fas fa-truck",
        "payments": "fas fa-credit-card",
        "email_manager": "fas fa-envelope",
        "locations": "fas fa-map-marker-alt",
        "shopify_integration": "fab fa-shopify",
        "accounts": "fas fa-user-circle",
        
        # Model-level icons
        "auth.group": "fas fa-users",
        
        # Accounts app
        "accounts.customuser": "fas fa-user",
        "accounts.companyrole": "fas fa-user-tag",
        "customers.shopifycustomer": "fas fa-user-circle",
        "customers.shopifycustomeraddress": "fas fa-map-marker-alt",
        "customers.customersynclog": "fas fa-sync-alt",
        
        # Customer Subscriptions app (8 models)
        "customer_subscriptions.sellingplan": "fas fa-calendar-check",
        "customer_subscriptions.customersubscription": "fas fa-sync-alt",
        "customer_subscriptions.subscriptionbillingattempt": "fas fa-credit-card",
        "customer_subscriptions.subscriptionsynclog": "fas fa-history",
        "customer_subscriptions.subscriptionaddress": "fas fa-map-marked-alt",
        "customer_subscriptions.orderaddressoverride": "fas fa-map-signs",
        "customer_subscriptions.productshippingconfig": "fas fa-cog",
        "customer_subscriptions.shippingcutofflog": "fas fa-clock",
        
        # Orders app
        "orders.shopifyorder": "fas fa-shopping-cart",
        "orders.shopifyorderlineitem": "fas fa-list",
        "orders.shopifyorderaddress": "fas fa-map-marker-alt",
        "orders.ordersynclog": "fas fa-sync-alt",
        
        # Skips app
        "skips.skip": "fas fa-forward",
        "skips.skipnotification": "fas fa-bell",
        "skips.subscriptionskip": "fas fa-step-forward",
        "skips.subscriptionskippolicy": "fas fa-tasks",
        
        # Products app
        "products.shopifyproduct": "fas fa-box-open",
        "products.shopifyproductvariant": "fas fa-boxes",
        "products.shopifyproductimage": "fas fa-image",
        "products.shopifyproductmetafield": "fas fa-tags",
        "products.productsynclog": "fas fa-sync-alt",
        
        # Inventory app
        "inventory.shopifylocation": "fas fa-map-pin",
        "inventory.shopifyinventoryitem": "fas fa-warehouse",
        "inventory.shopifyinventorylevel": "fas fa-layer-group",
        "inventory.inventoryadjustment": "fas fa-sliders-h",
        "inventory.inventorysynclog": "fas fa-sync-alt",
        
        # Shipping app (9 models)
        "shipping.shippingrate": "fas fa-dollar-sign",
        "shipping.shopifycarrierservice": "fas fa-truck",
        "shipping.shopifydeliveryprofile": "fas fa-clipboard-list",
        "shipping.shopifydeliveryzone": "fas fa-map-marked",
        "shipping.shopifydeliverymethod": "fas fa-shipping-fast",
        "shipping.shopifyfulfillmentorder": "fas fa-box-open",
        "shipping.shopifyfulfillmentservice": "fab fa-shopify",
        "shipping.shippingsynclog": "fas fa-sync-alt",
        "shipping.fulfillmenttrackinginfo": "fas fa-route",
        
        # Payments app
        "payments.shopifypaymentsaccount": "fas fa-university",
        "payments.shopifybalancetransaction": "fas fa-exchange-alt",
        "payments.shopifypayout": "fas fa-money-bill-wave",
        "payments.shopifybankaccount": "fas fa-piggy-bank",
        "payments.shopifydispute": "fas fa-gavel",
        "payments.shopifydisputeevidence": "fas fa-file-contract",
        "payments.shopifyfinancekyc": "fas fa-id-card",
        "payments.shopifypaymentssynclog": "fas fa-sync-alt",
        "email_manager.emailtemplate": "fas fa-envelope",
        "email_manager.emailhistory": "fas fa-paper-plane",
        "email_manager.emailconfiguration": "fas fa-cog",
        "email_manager.emailinbox": "fas fa-inbox",
        "email_manager.emailmessage": "fas fa-envelope-open",
        "email_manager.emailattachment": "fas fa-paperclip",
        "email_manager.emailguardian": "fas fa-shield-alt",
        "email_manager.securityalert": "fas fa-exclamation-triangle",
        "email_manager.emailautomation": "fas fa-magic",
        "email_manager.scheduledemail": "fas fa-calendar-alt",
        "email_manager.incomingmailconfiguration": "fas fa-mail-bulk",
        "email_manager.emailfolder": "fas fa-folder",
        "email_manager.emaillabel": "fas fa-tag",
        "email_manager.messagelabel": "fas fa-tags",
        "email_manager.emailguardianrule": "fas fa-shield",
        "email_manager.emailscanresult": "fas fa-search",
        "locations.country": "fas fa-flag",
        "locations.state": "fas fa-map",
        "locations.city": "fas fa-city",
        "locations.location": "fas fa-map-pin",
        
        # Accounts app (continued)
        "accounts.industrytype": "fas fa-industry",
        "accounts.companystaff": "fas fa-users",
        "accounts.bankdetail": "fas fa-university",
        "accounts.carddetail": "fas fa-credit-card",
        "accounts.payid": "fas fa-mobile-alt",
        "accounts.usersession": "fas fa-key",
        "accounts.companysite": "fas fa-building",
        
        # Skips app
        "skips.skipanalytics": "fas fa-chart-bar",
        
        # Shopify Integration app (4 models)
        "shopify_integration": "fab fa-shopify",
        "shopify_integration.shopifystore": "fas fa-store",
        "shopify_integration.syncoperation": "fas fa-sync",
        "shopify_integration.webhookendpoint": "fas fa-plug",
        "shopify_integration.apiratelimit": "fas fa-tachometer-alt",
    },
    
    # Icons for apps
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    # UI Tweaks
    "related_modal_active": False,
    "custom_css": "admin/css/custom.css",
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    
    # Change forms
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "accounts.CustomUser": "collapsible",
        "auth.Group": "vertical_tabs",
    },
    
    # Language chooser
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-brown",
    "accent": "accent-brown",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-brown",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# Shopify API settings
SHOPIFY_STORE_URL = os.getenv('SHOPIFY_STORE_URL')
SHOPIFY_API_KEY = os.getenv('SHOPIFY_API_KEY')
SHOPIFY_API_SECRET = os.getenv('SHOPIFY_API_SECRET')
SHOPIFY_ACCESS_TOKEN = os.getenv('SHOPIFY_ACCESS_TOKEN')
SHOPIFY_API_VERSION = os.getenv('SHOPIFY_API_VERSION', '2025-01')

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'shopify_integration': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Crispy Forms
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# CORS Configuration for Shopify Theme Integration
CORS_ALLOWED_ORIGINS = [
    "https://lavish-backend.endevops.net",
    "https://7fa66c-ac.myshopify.com",
    "https://viewing.endevops.net",  # Production frontend
    "https://lavish-backend.endevops.net",  # Production backend
    "http://viewing.endevops.net",  # Production frontend (http)
    "http://lavish-backend.endevops.net",  # Production backend (http)
    "http://127.0.0.1:9292",  # Shopify CLI local development
    "http://localhost:9292",
    "http://127.0.0.1:9293",  # Current Shopify theme port
    "http://localhost:9293",
    "http://127.0.0.1:8003",  # Django backend local development
    "http://localhost:8003",
    "http://127.0.0.1:8000",  # Frontend demo server local development
    "http://localhost:8000",
    "http://127.0.0.1:8080",  # Frontend demo server alternative port
    "http://localhost:8080",
    "http://127.0.0.1:9292",  # Shopify CLI local development (duplicate for clarity)
    "http://localhost:9292",   # Shopify CLI local development (duplicate for clarity)
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True  # For development only - disable in production

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}


# ============================================================================
# SHOPIFY CONFIGURATION
# ============================================================================

# Shopify Store Configuration
SHOPIFY_SHOP_DOMAIN = os.getenv('SHOPIFY_SHOP_DOMAIN', '7fa66c-ac.myshopify.com')
SHOPIFY_ACCESS_TOKEN = os.getenv('SHOPIFY_ACCESS_TOKEN', '')
SHOPIFY_API_KEY = os.getenv('SHOPIFY_API_KEY', '')
SHOPIFY_API_SECRET = os.getenv('SHOPIFY_API_SECRET', '')
SHOPIFY_API_VERSION = '2024-10'

# Sendal Shipping Integration
SENDAL_API_ENDPOINT = os.getenv('SENDAL_API_ENDPOINT', 'https://api.sendal.com/v1/rates')
SENDAL_API_KEY = os.getenv('SENDAL_API_KEY', '')

# Exchange Rate API for currency conversion
EXCHANGE_RATE_API_KEY = os.getenv('EXCHANGE_RATE_API_KEY', '')


# ============================================================================
# MULTI-CURRENCY CONFIGURATION
# ============================================================================

# Supported currencies (ISO 4217 codes)
SUPPORTED_CURRENCIES = [
    'USD',  # US Dollar
    'EUR',  # Euro
    'GBP',  # British Pound
    'CAD',  # Canadian Dollar
    'AUD',  # Australian Dollar
    'JPY',  # Japanese Yen
    'CNY',  # Chinese Yuan
    'CHF',  # Swiss Franc
    'SEK',  # Swedish Krona
    'NZD',  # New Zealand Dollar
]

# Default currency
DEFAULT_CURRENCY = 'USD'

# Currency display settings
CURRENCY_SETTINGS = {
    'USD': {'symbol': '$', 'position': 'before', 'decimal_separator': '.', 'thousand_separator': ','},
    'EUR': {'symbol': '€', 'position': 'after', 'decimal_separator': ',', 'thousand_separator': '.'},
    'GBP': {'symbol': '£', 'position': 'before', 'decimal_separator': '.', 'thousand_separator': ','},
    'CAD': {'symbol': 'C$', 'position': 'before', 'decimal_separator': '.', 'thousand_separator': ','},
    'AUD': {'symbol': 'A$', 'position': 'before', 'decimal_separator': '.', 'thousand_separator': ','},
    'JPY': {'symbol': '¥', 'position': 'before', 'decimal_separator': '', 'thousand_separator': ','},
    'CNY': {'symbol': '¥', 'position': 'before', 'decimal_separator': '.', 'thousand_separator': ','},
    'CHF': {'symbol': 'CHF', 'position': 'before', 'decimal_separator': '.', 'thousand_separator': "'"},
    'SEK': {'symbol': 'kr', 'position': 'after', 'decimal_separator': ',', 'thousand_separator': ' '},
    'NZD': {'symbol': 'NZ$', 'position': 'before', 'decimal_separator': '.', 'thousand_separator': ','},
}


# ============================================================================
# LOCALE AND INTERNATIONALIZATION
# ============================================================================

# Supported languages (ISO 639-1 codes)
SUPPORTED_LANGUAGES = [
    ('en', 'English'),
    ('fr', 'Français'),
    ('de', 'Deutsch'),
    ('es', 'Español'),
    ('it', 'Italiano'),
    ('ja', '日本語'),
    ('zh-cn', '简体中文'),
]

# Locale to currency mapping
LOCALE_CURRENCY_MAP = {
    'en-US': 'USD',
    'en-CA': 'CAD',
    'en-GB': 'GBP',
    'en-AU': 'AUD',
    'en-NZ': 'NZD',
    'fr-FR': 'EUR',
    'de-DE': 'EUR',
    'es-ES': 'EUR',
    'it-IT': 'EUR',
    'ja-JP': 'JPY',
    'zh-CN': 'CNY',
    'fr-CH': 'CHF',
    'de-CH': 'CHF',
    'sv-SE': 'SEK',
}

# Country to currency mapping
COUNTRY_CURRENCY_MAP = {
    'US': 'USD', 'CA': 'CAD', 'GB': 'GBP', 'AU': 'AUD', 'NZ': 'NZD',
    'JP': 'JPY', 'CN': 'CNY', 'CH': 'CHF', 'SE': 'SEK', 'NO': 'NOK',
    'DK': 'DKK',
    # EU countries
    'DE': 'EUR', 'FR': 'EUR', 'IT': 'EUR', 'ES': 'EUR', 'NL': 'EUR',
    'BE': 'EUR', 'AT': 'EUR', 'IE': 'EUR', 'PT': 'EUR', 'FI': 'EUR',
    'GR': 'EUR', 'LU': 'EUR', 'SI': 'EUR', 'SK': 'EUR', 'EE': 'EUR',
    'LV': 'EUR', 'LT': 'EUR', 'CY': 'EUR', 'MT': 'EUR',
}
