"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g!@oi#!t-u06qml(#6jm6=b!f-=f^%i6yb@nc+xrf%^2o0fei6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'lavish-backend.endevops.net',
    'viewing.endevops.net',
    '.myshopify.com',  # Allow all Shopify store domains
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Must be before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'crispy_forms',
    'import_export',
    
    # Custom apps
    'api',
    'accounts',
    'customers',
    'products',
    'orders',
    'inventory',
    'shipping',
    'payments',
    'shopify_integration',
    'locations',
    'skips',
    'customer_subscriptions',
    'email_manager',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'locations.shopify_currency_service.LocaleMiddleware',  # Currency and locale detection
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'locations.context_processors.currency_context',  # Currency context for templates
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'lavish_library.db',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Australia/Sydney'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# JAZZMIN CONFIGURATION - Lavish Library Admin Theme
# ============================================================================

JAZZMIN_SETTINGS = {
    # Site branding
    "site_title": "Lavish Library Admin",
    "site_header": "Lavish Library",
    "site_brand": "Lavish Library",
    "site_logo": None,
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "Welcome to Lavish Library Admin",
    "copyright": "Lavish Library",
    "search_model": ["auth.User", "customers.Customer", "orders.Order", "products.Product"],
    
    # User menu
    "user_avatar": None,
    
    # Top Menu
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "https://7fa66c-ac.myshopify.com/", "new_window": True},
        {"name": "Support", "url": "https://github.com/eo-nwanze/lavish/issues", "new_window": True},
        {"model": "auth.User"},
    ],
    
    # User menu (dropdown)
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/eo-nwanze/lavish/issues", "icon": "fas fa-life-ring", "new_window": True},
        {"model": "auth.user"}
    ],
    
    # Side Menu
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "auth",
        "customers",
        "customer_subscriptions",
        "orders",
        "skips",
        "products",
        "inventory",
        "shipping",
        "payments",
        "email_manager",
        "locations",
        "shopify_integration",
    ],
    
    # Icons for models - Font Awesome
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "customers.Customer": "fas fa-user-circle",
        "customers.CustomerAddress": "fas fa-map-marker-alt",
        "customers.CustomerPaymentMethod": "fas fa-credit-card",
        "customer_subscriptions.Subscription": "fas fa-sync",
        "customer_subscriptions.SubscriptionItem": "fas fa-box",
        "orders.Order": "fas fa-shopping-cart",
        "orders.OrderItem": "fas fa-list",
        "orders.Fulfillment": "fas fa-truck",
        "orders.FulfillmentLineItem": "fas fa-clipboard-list",
        "orders.Delivery": "fas fa-shipping-fast",
        "skips.Skip": "fas fa-forward",
        "skips.SkipNotification": "fas fa-bell",
        "products.Product": "fas fa-box-open",
        "products.ProductVariant": "fas fa-boxes",
        "inventory.InventoryItem": "fas fa-warehouse",
        "inventory.InventoryLevel": "fas fa-layer-group",
        "shipping.ShippingRate": "fas fa-dollar-sign",
        "shipping.ShippingZone": "fas fa-globe",
        "payments.Payment": "fas fa-money-bill-wave",
        "payments.Transaction": "fas fa-exchange-alt",
        "email_manager.EmailTemplate": "fas fa-envelope",
        "email_manager.EmailLog": "fas fa-paper-plane",
        "locations.Country": "fas fa-flag",
        "locations.State": "fas fa-map",
        "locations.City": "fas fa-city",
        "locations.Location": "fas fa-map-pin",
        "shopify_integration": "fab fa-shopify",
    },
    
    # Icons for apps
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    # UI Tweaks
    "related_modal_active": False,
    "custom_css": "admin/css/custom.css",
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    
    # Change forms
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    
    # Language chooser
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-purple",
    "accent": "accent-purple",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-purple",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# Shopify API settings
SHOPIFY_STORE_URL = os.getenv('SHOPIFY_STORE_URL')
SHOPIFY_API_KEY = os.getenv('SHOPIFY_API_KEY')
SHOPIFY_API_SECRET = os.getenv('SHOPIFY_API_SECRET')
SHOPIFY_ACCESS_TOKEN = os.getenv('SHOPIFY_ACCESS_TOKEN')
SHOPIFY_API_VERSION = os.getenv('SHOPIFY_API_VERSION', '2025-01')

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'shopify_integration': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Crispy Forms
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# CORS Configuration for Shopify Theme Integration
CORS_ALLOWED_ORIGINS = [
    "https://7fa66c-ac.myshopify.com",
    "https://viewing.endevops.net",  # Production frontend
    "https://lavish-backend.endevops.net",  # Production backend
    "http://viewing.endevops.net",  # Production frontend (http)
    "http://lavish-backend.endevops.net",  # Production backend (http)
    "http://127.0.0.1:9292",  # Shopify CLI local development
    "http://localhost:9292",
    "http://127.0.0.1:9293",  # Current Shopify theme port
    "http://localhost:9293",
    "http://127.0.0.1:8003",  # Django backend local development
    "http://localhost:8003",
]

CORS_ALLOW_ALL_ORIGINS = True  # For development only - disable in production
CORS_ALLOW_CREDENTIALS = True

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}


# ============================================================================
# SHOPIFY CONFIGURATION
# ============================================================================

# Shopify Store Configuration
SHOPIFY_SHOP_DOMAIN = os.getenv('SHOPIFY_SHOP_DOMAIN', '7fa66c-ac.myshopify.com')
SHOPIFY_ACCESS_TOKEN = os.getenv('SHOPIFY_ACCESS_TOKEN', '')
SHOPIFY_API_KEY = os.getenv('SHOPIFY_API_KEY', '')
SHOPIFY_API_SECRET = os.getenv('SHOPIFY_API_SECRET', '')
SHOPIFY_API_VERSION = '2024-10'

# Sendal Shipping Integration
SENDAL_API_ENDPOINT = os.getenv('SENDAL_API_ENDPOINT', 'https://api.sendal.com/v1/rates')
SENDAL_API_KEY = os.getenv('SENDAL_API_KEY', '')

# Exchange Rate API for currency conversion
EXCHANGE_RATE_API_KEY = os.getenv('EXCHANGE_RATE_API_KEY', '')


# ============================================================================
# MULTI-CURRENCY CONFIGURATION
# ============================================================================

# Supported currencies (ISO 4217 codes)
SUPPORTED_CURRENCIES = [
    'USD',  # US Dollar
    'EUR',  # Euro
    'GBP',  # British Pound
    'CAD',  # Canadian Dollar
    'AUD',  # Australian Dollar
    'JPY',  # Japanese Yen
    'CNY',  # Chinese Yuan
    'CHF',  # Swiss Franc
    'SEK',  # Swedish Krona
    'NZD',  # New Zealand Dollar
]

# Default currency
DEFAULT_CURRENCY = 'USD'

# Currency display settings
CURRENCY_SETTINGS = {
    'USD': {'symbol': '$', 'position': 'before', 'decimal_separator': '.', 'thousand_separator': ','},
    'EUR': {'symbol': '€', 'position': 'after', 'decimal_separator': ',', 'thousand_separator': '.'},
    'GBP': {'symbol': '£', 'position': 'before', 'decimal_separator': '.', 'thousand_separator': ','},
    'CAD': {'symbol': 'C$', 'position': 'before', 'decimal_separator': '.', 'thousand_separator': ','},
    'AUD': {'symbol': 'A$', 'position': 'before', 'decimal_separator': '.', 'thousand_separator': ','},
    'JPY': {'symbol': '¥', 'position': 'before', 'decimal_separator': '', 'thousand_separator': ','},
    'CNY': {'symbol': '¥', 'position': 'before', 'decimal_separator': '.', 'thousand_separator': ','},
    'CHF': {'symbol': 'CHF', 'position': 'before', 'decimal_separator': '.', 'thousand_separator': "'"},
    'SEK': {'symbol': 'kr', 'position': 'after', 'decimal_separator': ',', 'thousand_separator': ' '},
    'NZD': {'symbol': 'NZ$', 'position': 'before', 'decimal_separator': '.', 'thousand_separator': ','},
}


# ============================================================================
# LOCALE AND INTERNATIONALIZATION
# ============================================================================

# Supported languages (ISO 639-1 codes)
SUPPORTED_LANGUAGES = [
    ('en', 'English'),
    ('fr', 'Français'),
    ('de', 'Deutsch'),
    ('es', 'Español'),
    ('it', 'Italiano'),
    ('ja', '日本語'),
    ('zh-cn', '简体中文'),
]

# Locale to currency mapping
LOCALE_CURRENCY_MAP = {
    'en-US': 'USD',
    'en-CA': 'CAD',
    'en-GB': 'GBP',
    'en-AU': 'AUD',
    'en-NZ': 'NZD',
    'fr-FR': 'EUR',
    'de-DE': 'EUR',
    'es-ES': 'EUR',
    'it-IT': 'EUR',
    'ja-JP': 'JPY',
    'zh-CN': 'CNY',
    'fr-CH': 'CHF',
    'de-CH': 'CHF',
    'sv-SE': 'SEK',
}

# Country to currency mapping
COUNTRY_CURRENCY_MAP = {
    'US': 'USD', 'CA': 'CAD', 'GB': 'GBP', 'AU': 'AUD', 'NZ': 'NZD',
    'JP': 'JPY', 'CN': 'CNY', 'CH': 'CHF', 'SE': 'SEK', 'NO': 'NOK',
    'DK': 'DKK',
    # EU countries
    'DE': 'EUR', 'FR': 'EUR', 'IT': 'EUR', 'ES': 'EUR', 'NL': 'EUR',
    'BE': 'EUR', 'AT': 'EUR', 'IE': 'EUR', 'PT': 'EUR', 'FI': 'EUR',
    'GR': 'EUR', 'LU': 'EUR', 'SI': 'EUR', 'SK': 'EUR', 'EE': 'EUR',
    'LV': 'EUR', 'LT': 'EUR', 'CY': 'EUR', 'MT': 'EUR',
}
