# Generated by Django 4.2.23 on 2025-10-10 16:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyPaymentsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(max_length=255, unique=True)),
                ('account_opener_name', models.CharField(blank=True, max_length=255)),
                ('activated', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=2)),
                ('default_currency', models.CharField(max_length=3)),
                ('onboardable', models.BooleanField(default=False)),
                ('payout_statement_descriptor', models.CharField(blank=True, max_length=255)),
                ('charge_statement_descriptor', models.CharField(blank=True, max_length=255)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shopify Payments Account',
                'verbose_name_plural': 'Shopify Payments Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopifyPaymentsSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('full_sync', 'Full Sync'), ('balance_transactions', 'Balance Transactions'), ('payouts', 'Payouts'), ('disputes', 'Disputes'), ('bank_accounts', 'Bank Accounts')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('items_processed', models.IntegerField(default=0)),
                ('items_created', models.IntegerField(default=0)),
                ('items_updated', models.IntegerField(default=0)),
                ('items_failed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=255)),
            ],
            options={
                'verbose_name': 'Payments Sync Log',
                'verbose_name_plural': 'Payments Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopifyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(max_length=255, unique=True)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_number_last4', models.CharField(blank=True, max_length=4)),
                ('routing_number', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=2)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending'), ('errored', 'Errored')], max_length=50)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='payments.shopifypaymentsaccount')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopifyPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_transit', 'In Transit'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_code', models.CharField(max_length=3)),
                ('bank_account_id', models.CharField(blank=True, max_length=255)),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='payments.shopifypaymentsaccount')),
            ],
            options={
                'verbose_name': 'Payout',
                'verbose_name_plural': 'Payouts',
                'ordering': ['-payout_date', '-created_at'],
                'indexes': [models.Index(fields=['status', 'payout_date'], name='payments_sh_status_92aa59_idx'), models.Index(fields=['currency_code'], name='payments_sh_currenc_20c4ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopifyDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('needs_response', 'Needs Response'), ('under_review', 'Under Review'), ('charge_refunded', 'Charge Refunded'), ('won', 'Won'), ('lost', 'Lost')], max_length=50)),
                ('reason', models.CharField(choices=[('bank_cannot_process', 'Bank Cannot Process'), ('credit_not_processed', 'Credit Not Processed'), ('customer_initiated', 'Customer Initiated'), ('debit_not_authorized', 'Debit Not Authorized'), ('duplicate', 'Duplicate'), ('fraudulent', 'Fraudulent'), ('general', 'General'), ('incorrect_account_details', 'Incorrect Account Details'), ('insufficient_funds', 'Insufficient Funds'), ('product_not_received', 'Product Not Received'), ('product_unacceptable', 'Product Unacceptable'), ('subscription_canceled', 'Subscription Canceled'), ('unrecognized', 'Unrecognized')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_code', models.CharField(max_length=3)),
                ('order_id', models.CharField(blank=True, max_length=255)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_due_by', models.DateTimeField(blank=True, null=True)),
                ('evidence_sent_on', models.DateTimeField(blank=True, null=True)),
                ('finalized_on', models.DateTimeField(blank=True, null=True)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='payments.shopifypaymentsaccount')),
            ],
            options={
                'verbose_name': 'Dispute',
                'verbose_name_plural': 'Disputes',
                'ordering': ['-initiated_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'initiated_at'], name='payments_sh_status_b693b3_idx'), models.Index(fields=['reason'], name='payments_sh_reason_7721ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopifyBalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(max_length=255, unique=True)),
                ('transaction_type', models.CharField(choices=[('charge', 'Charge'), ('refund', 'Refund'), ('dispute', 'Dispute'), ('reserve', 'Reserve'), ('adjustment', 'Adjustment'), ('credit', 'Credit'), ('debit', 'Debit'), ('payout', 'Payout'), ('payout_failure', 'Payout Failure'), ('payout_cancellation', 'Payout Cancellation')], max_length=50)),
                ('test', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_code', models.CharField(max_length=3)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(blank=True, choices=[('charge', 'Charge'), ('refund', 'Refund'), ('dispute', 'Dispute'), ('reserve', 'Reserve'), ('adjustment', 'Adjustment'), ('payout', 'Payout')], max_length=50)),
                ('source_order_transaction_id', models.CharField(blank=True, max_length=255)),
                ('associated_order_id', models.CharField(blank=True, max_length=255)),
                ('associated_payout_id', models.CharField(blank=True, max_length=255)),
                ('associated_payout_status', models.CharField(blank=True, max_length=50)),
                ('adjustment_reason', models.TextField(blank=True)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_transactions', to='payments.shopifypaymentsaccount')),
            ],
            options={
                'verbose_name': 'Balance Transaction',
                'verbose_name_plural': 'Balance Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_type', 'created_at'], name='payments_sh_transac_b2b4dc_idx'), models.Index(fields=['source_type', 'source_id'], name='payments_sh_source__781e57_idx'), models.Index(fields=['associated_payout_id'], name='payments_sh_associa_12b961_idx')],
            },
        ),
    ]
