# Generated by Django 5.2.7 on 2025-10-10 17:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyDisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(max_length=255, unique=True)),
                ('submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dispute Evidence',
                'verbose_name_plural': 'Dispute Evidence',
            },
        ),
        migrations.CreateModel(
            name='ShopifyFinanceKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('business_type', models.CharField(blank=True, choices=[('corporation', 'Corporation'), ('free_zone_establishment', 'Free Zone Establishment'), ('free_zone_llc', 'Free Zone LLC'), ('government', 'Government'), ('incorporated_partnership', 'Incorporated Partnership'), ('individual', 'Individual'), ('llc', 'LLC'), ('non_profit', 'Non Profit'), ('non_profit_incorporated', 'Non Profit Incorporated'), ('non_profit_registered_charity', 'Non Profit Registered Charity'), ('non_profit_unincorporated', 'Non Profit Unincorporated'), ('non_profit_unincorporated_association', 'Non Profit Unincorporated Association'), ('not_set', 'Not Set'), ('partnership', 'Partnership'), ('private_corporation', 'Private Corporation'), ('private_multi_member_llc', 'Private Multi Member LLC'), ('private_partnership', 'Private Partnership'), ('private_single_member_llc', 'Private Single Member LLC'), ('private_unincorporated_association', 'Private Unincorporated Association'), ('public_company', 'Public Company'), ('public_corporation', 'Public Corporation'), ('public_partnership', 'Public Partnership'), ('sole_establishment', 'Sole Establishment'), ('sole_prop', 'Sole Proprietorship'), ('unincorporated_partnership', 'Unincorporated Partnership')], max_length=50)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('zone', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('industry_category', models.CharField(blank=True, max_length=255)),
                ('industry_category_label', models.CharField(blank=True, max_length=255)),
                ('industry_code', models.IntegerField(blank=True, null=True)),
                ('industry_subcategory_label', models.CharField(blank=True, max_length=255)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('owner_first_name', models.CharField(blank=True, max_length=100)),
                ('owner_last_name', models.CharField(blank=True, max_length=100)),
                ('owner_phone', models.CharField(blank=True, max_length=50)),
                ('tax_id_type', models.CharField(blank=True, choices=[('ein', 'EIN - Employer Identification Number'), ('ssn', 'SSN - Social Security Number'), ('abn', 'ABN - Australian Business Number'), ('acn', 'ACN - Australian Company Number'), ('gst', 'GST - Goods and Services Tax'), ('vat', 'VAT - Value Added Tax'), ('other', 'Other')], max_length=50)),
                ('tax_id_value', models.CharField(blank=True, max_length=255)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Finance KYC Information',
                'verbose_name_plural': 'Finance KYC Information',
            },
        ),
        migrations.AddField(
            model_name='shopifydispute',
            name='dispute_type',
            field=models.CharField(choices=[('chargeback', 'Chargeback'), ('inquiry', 'Inquiry')], default='chargeback', max_length=50),
        ),
        migrations.AddField(
            model_name='shopifydispute',
            name='network_reason_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='shopifydispute',
            index=models.Index(fields=['dispute_type'], name='payments_sh_dispute_8124a1_idx'),
        ),
        migrations.AddField(
            model_name='shopifydisputeevidence',
            name='dispute',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='payments.shopifydispute'),
        ),
        migrations.AddField(
            model_name='shopifyfinancekyc',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_info', to='payments.shopifypaymentsaccount'),
        ),
    ]
