# Generated by Django 4.2.23 on 2025-11-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_shopifydisputeevidence_shopifyfinancekyc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifypaymentsaccount',
            name='account_opener_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
