# Generated by Django 4.2.23 on 2025-11-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_shopifypaymentsaccount_account_opener_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifybalancetransaction',
            name='adjustment_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
