# Generated by Django 4.2.23 on 2025-11-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_shopifybalancetransaction_adjustment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifybalancetransaction',
            name='associated_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopifybalancetransaction',
            name='associated_payout_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopifybalancetransaction',
            name='associated_payout_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopifybalancetransaction',
            name='source_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopifybalancetransaction',
            name='source_order_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopifybalancetransaction',
            name='source_type',
            field=models.CharField(blank=True, choices=[('charge', 'Charge'), ('refund', 'Refund'), ('dispute', 'Dispute'), ('reserve', 'Reserve'), ('adjustment', 'Adjustment'), ('payout', 'Payout')], max_length=50, null=True),
        ),
    ]
