# Generated by Django 4.2.23 on 2025-12-05 00:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_shopifybalancetransaction_associated_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterpayConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Afterpay Configuration', help_text='Configuration name for identification', max_length=255)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox (Testing)'), ('production', 'Production (Live)')], default='sandbox', help_text='API environment (sandbox for testing, production for live)', max_length=20)),
                ('region', models.CharField(choices=[('US', 'United States'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('CA', 'Canada'), ('GB', 'United Kingdom')], default='US', help_text='Merchant region', max_length=2)),
                ('merchant_id', models.CharField(help_text='Afterpay Merchant ID (username for Basic Auth)', max_length=255)),
                ('secret_key', models.CharField(help_text='Afterpay Secret Key (password for Basic Auth)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this configuration')),
                ('is_default', models.BooleanField(default=False, help_text='Set as default Afterpay configuration')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum payment amount (fetched from Afterpay API)', max_digits=10, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum payment amount (fetched from Afterpay API)', max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', help_text='Default currency code', max_length=3)),
                ('config_last_fetched', models.DateTimeField(blank=True, help_text='Last time configuration was fetched from Afterpay', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Afterpay Configuration',
                'verbose_name_plural': 'Afterpay Configurations',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AfterpayWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text='Type of webhook event', max_length=100)),
                ('afterpay_order_id', models.CharField(blank=True, help_text='Afterpay order ID from webhook', max_length=255)),
                ('merchant_reference', models.CharField(blank=True, help_text='Merchant reference from webhook', max_length=255)),
                ('processed', models.BooleanField(default=False, help_text='Whether this webhook has been processed')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When webhook was processed', null=True)),
                ('payload', models.JSONField(help_text='Full webhook payload')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
            ],
            options={
                'verbose_name': 'Afterpay Webhook',
                'verbose_name_plural': 'Afterpay Webhooks',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_type', 'processed'], name='payments_af_event_t_d5612b_idx'), models.Index(fields=['afterpay_order_id'], name='payments_af_afterpa_0ddfa4_idx'), models.Index(fields=['merchant_reference'], name='payments_af_merchan_91ebd3_idx')],
            },
        ),
        migrations.CreateModel(
            name='AfterpayCheckout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('afterpay_token', models.CharField(help_text='Token returned from Afterpay checkout creation', max_length=255, unique=True)),
                ('afterpay_order_id', models.CharField(blank=True, help_text='Afterpay Order ID (after auth/capture)', max_length=255, null=True)),
                ('merchant_reference', models.CharField(help_text="Merchant's order reference/ID", max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total order amount', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('customer_email', models.EmailField(help_text='Customer email address', max_length=254)),
                ('customer_first_name', models.CharField(blank=True, max_length=255)),
                ('customer_last_name', models.CharField(blank=True, max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('expired', 'Expired'), ('captured', 'Captured'), ('auth_approved', 'Auth Approved'), ('cancelled', 'Cancelled')], default='created', help_text='Current checkout/payment status', max_length=20)),
                ('payment_state', models.CharField(blank=True, help_text='Afterpay payment state', max_length=50)),
                ('redirect_checkout_url', models.URLField(help_text='URL to redirect customer for Afterpay checkout', max_length=500)),
                ('expires_at', models.DateTimeField(help_text='When the checkout token expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopify_order_id', models.CharField(blank=True, help_text='Associated Shopify order ID', max_length=255, null=True)),
                ('subscription_id', models.CharField(blank=True, help_text='Associated subscription ID', max_length=255, null=True)),
                ('configuration', models.ForeignKey(help_text='Afterpay configuration used for this checkout', on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='payments.afterpayconfiguration')),
            ],
            options={
                'verbose_name': 'Afterpay Checkout',
                'verbose_name_plural': 'Afterpay Checkouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AfterpayRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('afterpay_refund_id', models.CharField(help_text="Afterpay's refund ID", max_length=255, unique=True)),
                ('request_id', models.UUIDField(default=uuid.uuid4, help_text='Idempotency key for safe retries')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Refund amount', max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('merchant_reference', models.CharField(help_text="Merchant's refund reference", max_length=255)),
                ('refund_merchant_reference', models.CharField(blank=True, help_text='Unique reference for this refund event', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('refunded_at', models.DateTimeField(help_text='When Afterpay processed the refund')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for refund')),
                ('raw_response', models.JSONField(blank=True, help_text='Full raw response from Afterpay', null=True)),
                ('checkout', models.ForeignKey(help_text='Associated checkout/payment', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.afterpaycheckout')),
            ],
            options={
                'verbose_name': 'Afterpay Refund',
                'verbose_name_plural': 'Afterpay Refunds',
                'ordering': ['-refunded_at'],
                'indexes': [models.Index(fields=['checkout', 'status'], name='payments_af_checkou_db753b_idx'), models.Index(fields=['merchant_reference'], name='payments_af_merchan_884707_idx')],
            },
        ),
        migrations.CreateModel(
            name='AfterpayPaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('afterpay_event_id', models.CharField(help_text="Afterpay's event ID", max_length=255, unique=True)),
                ('event_type', models.CharField(choices=[('AUTH_APPROVED', 'Authorization Approved'), ('CAPTURED', 'Payment Captured'), ('REFUNDED', 'Payment Refunded'), ('VOIDED', 'Payment Voided'), ('DECLINED', 'Payment Declined'), ('EXPIRED', 'Authorization Expired')], help_text='Type of payment event', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount for this event', max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('merchant_reference', models.CharField(blank=True, help_text='Merchant reference for this specific event', max_length=255)),
                ('event_created_at', models.DateTimeField(help_text='When Afterpay created this event')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When authorization expires (for AUTH_APPROVED events)', null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When this event was recorded in our system')),
                ('raw_response', models.JSONField(blank=True, help_text='Full raw response from Afterpay', null=True)),
                ('checkout', models.ForeignKey(help_text='Associated checkout session', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.afterpaycheckout')),
            ],
            options={
                'verbose_name': 'Afterpay Payment Event',
                'verbose_name_plural': 'Afterpay Payment Events',
                'ordering': ['-event_created_at'],
                'indexes': [models.Index(fields=['checkout', 'event_type'], name='payments_af_checkou_df00cf_idx'), models.Index(fields=['event_created_at'], name='payments_af_event_c_925461_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='afterpaycheckout',
            index=models.Index(fields=['afterpay_token'], name='payments_af_afterpa_be9c16_idx'),
        ),
        migrations.AddIndex(
            model_name='afterpaycheckout',
            index=models.Index(fields=['merchant_reference'], name='payments_af_merchan_127e3e_idx'),
        ),
        migrations.AddIndex(
            model_name='afterpaycheckout',
            index=models.Index(fields=['status'], name='payments_af_status_f185ad_idx'),
        ),
        migrations.AddIndex(
            model_name='afterpaycheckout',
            index=models.Index(fields=['shopify_order_id'], name='payments_af_shopify_82f1eb_idx'),
        ),
    ]
