# Generated by Django 5.2.7 on 2025-10-10 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('bulk_import', 'Bulk Import'), ('single_update', 'Single Update'), ('webhook_update', 'Webhook Update')], max_length=20)),
                ('orders_processed', models.IntegerField(default=0)),
                ('orders_created', models.IntegerField(default=0)),
                ('orders_updated', models.IntegerField(default=0)),
                ('line_items_processed', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopifyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(help_text='Shopify Global ID', max_length=100, unique=True)),
                ('order_number', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(help_text='Order name like #1001', max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('financial_status', models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded'), ('voided', 'Voided')], max_length=20)),
                ('fulfillment_status', models.CharField(blank=True, choices=[('fulfilled', 'Fulfilled'), ('null', 'Unfulfilled'), ('partial', 'Partially Fulfilled'), ('restocked', 'Restocked')], max_length=20, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_shipping_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency_code', models.CharField(default='AUD', max_length=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending Sync'), ('error', 'Sync Error')], default='synced', max_length=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.shopifycustomer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopifyOrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing')], max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('address1', models.CharField(blank=True, max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('province_code', models.CharField(blank=True, max_length=10)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='orders.shopifyorder')),
            ],
            options={
                'ordering': ['order', 'address_type'],
            },
        ),
        migrations.CreateModel(
            name='ShopifyOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(help_text='Shopify Line Item ID', max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('variant_title', models.CharField(blank=True, max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('properties', models.JSONField(blank=True, default=list)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='orders.shopifyorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.shopifyproduct')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.shopifyproductvariant')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='shopifyorder',
            index=models.Index(fields=['order_number'], name='orders_shop_order_n_fe6c27_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyorder',
            index=models.Index(fields=['shopify_id'], name='orders_shop_shopify_d6aa50_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyorder',
            index=models.Index(fields=['financial_status'], name='orders_shop_financi_d6a887_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyorder',
            index=models.Index(fields=['fulfillment_status'], name='orders_shop_fulfill_9b10e1_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyorder',
            index=models.Index(fields=['customer'], name='orders_shop_custome_575e65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shopifyorderaddress',
            unique_together={('order', 'address_type')},
        ),
        migrations.AddIndex(
            model_name='shopifyorderlineitem',
            index=models.Index(fields=['shopify_id'], name='orders_shop_shopify_2617eb_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyorderlineitem',
            index=models.Index(fields=['order'], name='orders_shop_order_i_20cd98_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyorderlineitem',
            index=models.Index(fields=['sku'], name='orders_shop_sku_a5c2ba_idx'),
        ),
    ]
