# Generated by Django 4.2.23 on 2025-11-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_shopifyorderlineitem_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyorderaddress',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
