# Generated by Django 4.2.23 on 2025-12-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_shopifyorderaddress_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyorder',
            name='note',
            field=models.TextField(blank=True, help_text='Order notes'),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated tags'),
        ),
    ]
