# Generated by Django 5.2.7 on 2025-10-10 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('bulk_import', 'Bulk Import'), ('single_update', 'Single Update'), ('webhook_update', 'Webhook Update')], max_length=20)),
                ('products_processed', models.IntegerField(default=0)),
                ('products_created', models.IntegerField(default=0)),
                ('products_updated', models.IntegerField(default=0)),
                ('variants_processed', models.IntegerField(default=0)),
                ('images_processed', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopifyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(help_text='Shopify Global ID', max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('handle', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(blank=True, max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('DRAFT', 'Draft')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Product tags as JSON array')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending Sync'), ('error', 'Sync Error')], default='synced', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['handle'], name='products_sh_handle_3b6fd2_idx'), models.Index(fields=['shopify_id'], name='products_sh_shopify_d54499_idx'), models.Index(fields=['status'], name='products_sh_status_c8de08_idx'), models.Index(fields=['product_type'], name='products_sh_product_e174a8_idx'), models.Index(fields=['vendor'], name='products_sh_vendor_b20bba_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopifyProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(help_text='Shopify Image ID', max_length=100, unique=True)),
                ('src', models.URLField(max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(default=1)),
                ('variant_ids', models.JSONField(blank=True, default=list, help_text='Associated variant IDs as JSON array')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.shopifyproduct')),
            ],
            options={
                'ordering': ['product', 'position'],
                'indexes': [models.Index(fields=['shopify_id'], name='products_sh_shopify_d3db5b_idx'), models.Index(fields=['product', 'position'], name='products_sh_product_663ade_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopifyProductMetafield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(help_text='Shopify Metafield ID', max_length=100, unique=True)),
                ('namespace', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('value_type', models.CharField(default='string', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metafields', to='products.shopifyproduct')),
            ],
            options={
                'ordering': ['product', 'namespace', 'key'],
                'indexes': [models.Index(fields=['shopify_id'], name='products_sh_shopify_a4f51b_idx'), models.Index(fields=['product', 'namespace'], name='products_sh_product_7691a8_idx'), models.Index(fields=['namespace', 'key'], name='products_sh_namespa_f5164e_idx')],
                'unique_together': {('product', 'namespace', 'key')},
            },
        ),
        migrations.CreateModel(
            name='ShopifyProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(help_text='Shopify Variant ID', max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_per_item', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inventory_quantity', models.IntegerField(default=0)),
                ('inventory_policy', models.CharField(choices=[('deny', 'Deny'), ('continue', 'Continue')], default='deny', max_length=20)),
                ('inventory_management', models.CharField(blank=True, max_length=50)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('weight_unit', models.CharField(default='kg', max_length=10)),
                ('option1', models.CharField(blank=True, max_length=255)),
                ('option2', models.CharField(blank=True, max_length=255)),
                ('option3', models.CharField(blank=True, max_length=255)),
                ('available', models.BooleanField(default=True)),
                ('requires_shipping', models.BooleanField(default=True)),
                ('taxable', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.shopifyproduct')),
            ],
            options={
                'ordering': ['product', 'position'],
                'indexes': [models.Index(fields=['sku'], name='products_sh_sku_98fe36_idx'), models.Index(fields=['shopify_id'], name='products_sh_shopify_d877b9_idx'), models.Index(fields=['product', 'position'], name='products_sh_product_a97e23_idx')],
            },
        ),
    ]
