# Generated by Django 4.2.23 on 2025-11-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyproduct',
            name='created_in_django',
            field=models.BooleanField(default=False, help_text='True if product was created in Django (not imported from Shopify)'),
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='last_pushed_to_shopify',
            field=models.DateTimeField(blank=True, help_text='Last time product was pushed to Shopify', null=True),
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='needs_shopify_push',
            field=models.BooleanField(default=False, help_text='True if product needs to be pushed to Shopify'),
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='shopify_push_error',
            field=models.TextField(blank=True, help_text='Error message if push to Shopify failed'),
        ),
    ]
