# Generated by Django 4.2.23 on 2025-12-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_shopifyproductimage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyproductimage',
            name='shopify_id',
            field=models.CharField(blank=True, help_text='Shopify Image ID', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shopifyproductmetafield',
            name='shopify_id',
            field=models.CharField(blank=True, help_text='Shopify Metafield ID', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shopifyproductvariant',
            name='shopify_id',
            field=models.CharField(blank=True, help_text='Shopify Variant ID', max_length=100, null=True, unique=True),
        ),
    ]
