# Generated by Django 4.2.23 on 2025-12-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_shopifyproductimage_shopify_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shopifyproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
