# Generated by Django 5.2.7 on 2025-10-10 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('bulk_import', 'Bulk Import'), ('single_update', 'Single Update'), ('webhook_update', 'Webhook Update'), ('adjustment', 'Adjustment')], max_length=20)),
                ('items_processed', models.IntegerField(default=0)),
                ('items_created', models.IntegerField(default=0)),
                ('items_updated', models.IntegerField(default=0)),
                ('levels_processed', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopifyInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(help_text='Shopify Inventory Item ID', max_length=100, unique=True)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('tracked', models.BooleanField(default=True)),
                ('requires_shipping', models.BooleanField(default=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending Sync'), ('error', 'Sync Error')], default='synced', max_length=20)),
                ('variant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_item', to='products.shopifyproductvariant')),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='ShopifyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(help_text='Shopify Location ID', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address1', models.CharField(blank=True, max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('legacy', models.BooleanField(default=False)),
                ('fulfills_online_orders', models.BooleanField(default=True)),
                ('fulfillment_service', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['shopify_id'], name='inventory_s_shopify_96ca2a_idx'), models.Index(fields=['active'], name='inventory_s_active_7dfced_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopifyInventoryLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.IntegerField(default=0, help_text='Available quantity')),
                ('committed', models.IntegerField(default=0, help_text='Committed quantity')),
                ('incoming', models.IntegerField(default=0, help_text='Incoming quantity')),
                ('on_hand', models.IntegerField(default=0, help_text='On hand quantity')),
                ('updated_at', models.DateTimeField()),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='inventory.shopifyinventoryitem')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_levels', to='inventory.shopifylocation')),
            ],
            options={
                'ordering': ['inventory_item', 'location'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease'), ('recount', 'Recount'), ('correction', 'Correction')], max_length=20)),
                ('quantity_delta', models.IntegerField(help_text='Change in quantity (positive or negative)')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('quantity_before', models.IntegerField()),
                ('quantity_after', models.IntegerField()),
                ('adjusted_by', models.CharField(blank=True, help_text='User who made the adjustment', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.shopifyinventoryitem')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.shopifylocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shopifyinventoryitem',
            index=models.Index(fields=['shopify_id'], name='inventory_s_shopify_3ab5bb_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyinventoryitem',
            index=models.Index(fields=['sku'], name='inventory_s_sku_176c48_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyinventoryitem',
            index=models.Index(fields=['tracked'], name='inventory_s_tracked_80e861_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyinventorylevel',
            index=models.Index(fields=['inventory_item', 'location'], name='inventory_s_invento_c72ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyinventorylevel',
            index=models.Index(fields=['available'], name='inventory_s_availab_728727_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shopifyinventorylevel',
            unique_together={('inventory_item', 'location')},
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['inventory_item', 'location'], name='inventory_i_invento_ee8361_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['adjustment_type'], name='inventory_i_adjustm_1dd667_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['-created_at'], name='inventory_i_created_9641aa_idx'),
        ),
    ]
