# Generated by Django 4.2.23 on 2025-12-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_shopifyinventoryitem_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyinventorylevel',
            name='last_pushed_to_shopify',
            field=models.DateTimeField(blank=True, help_text='When last pushed to Shopify', null=True),
        ),
        migrations.AddField(
            model_name='shopifyinventorylevel',
            name='needs_shopify_push',
            field=models.BooleanField(default=False, help_text='True if needs push to Shopify'),
        ),
        migrations.AddField(
            model_name='shopifyinventorylevel',
            name='shopify_push_error',
            field=models.TextField(blank=True, help_text='Last push error message'),
        ),
        migrations.AddIndex(
            model_name='shopifyinventorylevel',
            index=models.Index(fields=['needs_shopify_push'], name='inventory_s_needs_s_1184b1_idx'),
        ),
    ]
