# Generated by Django 4.2.23 on 2025-12-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_shopifyinventorylevel_last_pushed_to_shopify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyinventoryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shopifyinventoryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shopifylocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shopifylocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
