# Generated by Django 4.2.23 on 2025-11-29 11:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_subscription_contract_id', models.CharField(help_text='Shopify subscription contract ID', max_length=255, unique=True)),
                ('shopify_customer_id', models.CharField(help_text='Shopify customer ID', max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=200)),
                ('subscription_name', models.CharField(help_text='Product/subscription name', max_length=200)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('bi_monthly', 'Bi-Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('start_date', models.DateField(help_text='Subscription start date')),
                ('next_order_date', models.DateField(help_text='Next scheduled order date')),
                ('next_billing_date', models.DateField(help_text='Next billing date')),
                ('last_order_date', models.DateField(blank=True, help_text='Last order fulfillment date', null=True)),
                ('product_price', models.DecimalField(decimal_places=2, help_text='Base product price', max_digits=10)),
                ('shipping_price', models.DecimalField(decimal_places=2, help_text='Shipping cost', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total per billing cycle', max_digits=10)),
                ('currency_code', models.CharField(default='GBP', max_length=3)),
                ('skips_used_this_year', models.IntegerField(default=0, help_text='Skips used in current calendar year')),
                ('consecutive_skips', models.IntegerField(default=0, help_text='Current consecutive skip count')),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Subscription',
                'verbose_name_plural': 'Customer Subscriptions',
                'ordering': ['-next_order_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionSkipPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Policy name (e.g., 'Standard Skip Policy')", max_length=100)),
                ('max_skips_per_year', models.IntegerField(default=4, help_text='Maximum skips allowed per calendar year')),
                ('max_consecutive_skips', models.IntegerField(default=2, help_text='Maximum consecutive skips allowed')),
                ('advance_notice_days', models.IntegerField(default=7, help_text='Days before next order customer must skip')),
                ('skip_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee charged for skipping', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skip Policy',
                'verbose_name_plural': 'Skip Policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionSkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skip_type', models.CharField(choices=[('manual', 'Manual Customer Request'), ('auto', 'Automatic System Skip'), ('admin', 'Admin Override')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('original_order_date', models.DateField(help_text='Original scheduled order date')),
                ('original_billing_date', models.DateField(help_text='Original billing date')),
                ('new_order_date', models.DateField(help_text='New rescheduled order date')),
                ('new_billing_date', models.DateField(help_text='New rescheduled billing date')),
                ('reason', models.CharField(blank=True, help_text='Customer-provided reason', max_length=100)),
                ('reason_details', models.TextField(blank=True, help_text='Additional details')),
                ('skip_fee_charged', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('refund_issued', models.BooleanField(default=False, help_text='Whether any refund was issued')),
                ('shopify_order_id', models.CharField(blank=True, help_text='Shopify order ID that was skipped', max_length=255, null=True)),
                ('shopify_synced', models.BooleanField(default=False, help_text='Whether skip synced to Shopify')),
                ('shopify_sync_error', models.TextField(blank=True, help_text='Error message if sync failed')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes about this skip')),
                ('processed_by', models.CharField(blank=True, help_text='Staff member who processed', max_length=100)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When skip was requested')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When skip was confirmed', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='If skip was cancelled', null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips', to='skips.customersubscription')),
            ],
            options={
                'verbose_name': 'Subscription Skip',
                'verbose_name_plural': 'Subscription Skips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkipNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('skip_confirmed', 'Skip Confirmed'), ('skip_reminder', 'Skip Reminder'), ('skip_expiring', 'Skips Expiring'), ('skip_limit_reached', 'Skip Limit Reached')], max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], default='email', max_length=10)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('skip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='skips.subscriptionskip')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skip_notifications', to='skips.customersubscription')),
            ],
            options={
                'verbose_name': 'Skip Notification',
                'verbose_name_plural': 'Skip Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkipAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_skips', models.IntegerField(default=0)),
                ('confirmed_skips', models.IntegerField(default=0)),
                ('cancelled_skips', models.IntegerField(default=0)),
                ('failed_skips', models.IntegerField(default=0)),
                ('unique_customers', models.IntegerField(default=0)),
                ('new_skippers', models.IntegerField(default=0, help_text='Customers skipping for first time')),
                ('repeat_skippers', models.IntegerField(default=0)),
                ('revenue_deferred', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('skip_fees_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('top_reasons', models.JSONField(blank=True, default=dict)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=255)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Skip Analytics',
                'verbose_name_plural': 'Skip Analytics',
                'ordering': ['-period_start'],
                'unique_together': {('period_type', 'period_start', 'period_end')},
            },
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='skip_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='skips.subscriptionskippolicy'),
        ),
        migrations.AddIndex(
            model_name='subscriptionskip',
            index=models.Index(fields=['subscription', 'status'], name='skips_subsc_subscri_b7e070_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionskip',
            index=models.Index(fields=['original_order_date'], name='skips_subsc_origina_fb0c07_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionskip',
            index=models.Index(fields=['status', 'created_at'], name='skips_subsc_status_4b8206_idx'),
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['shopify_customer_id', 'status'], name='skips_custo_shopify_1b7245_idx'),
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['next_order_date'], name='skips_custo_next_or_f8ee94_idx'),
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['status', 'next_order_date'], name='skips_custo_status_d6c8c7_idx'),
        ),
    ]
