# Generated by Django 4.2.23 on 2025-11-30 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_subscriptions', '0009_remove_customersubscription_cancellation_reason_and_more'),
        ('skips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skipnotification',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skip_notifications', to='customer_subscriptions.customersubscription'),
        ),
        migrations.AlterField(
            model_name='subscriptionskip',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips', to='customer_subscriptions.customersubscription'),
        ),
        migrations.DeleteModel(
            name='CustomerSubscription',
        ),
    ]
