# Generated by Django 5.1 on 2025-04-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0002_alter_emailhistory_email_type_and_more'),
    ]

    operations = [
    ]
