# Generated by Django 4.2.10 on 2025-04-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0003_auto_20250406_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailhistory',
            name='email_type',
            field=models.CharField(choices=[('contact_form', 'Contact Form Notification'), ('appointment_request', 'Appointment Request'), ('appointment_confirmation', 'Appointment Confirmation'), ('appointment_reminder', 'Appointment Reminder'), ('appointment_cancellation', 'Appointment Cancellation'), ('test_email', 'Test Email Configuration'), ('newsletter', 'Newsletter'), ('scheduled_email', 'Scheduled Email'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('contact_form', 'Contact Form Notification'), ('appointment_request', 'Appointment Request'), ('appointment_confirmation', 'Appointment Confirmation'), ('appointment_reminder', 'Appointment Reminder'), ('appointment_cancellation', 'Appointment Cancellation'), ('newsletter', 'Newsletter'), ('welcome', 'Welcome Email'), ('custom', 'Custom Email')], default='custom', max_length=50),
        ),
    ]
