# Generated by Django 4.2.10 on 2025-04-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0004_alter_emailhistory_email_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('contact_form', 'Contact Form Notification'), ('appointment_request', 'Appointment Request'), ('appointment_confirmation', 'Appointment Confirmation'), ('appointment_reminder', 'Appointment Reminder'), ('appointment_cancellation', 'Appointment Cancellation'), ('newsletter', 'Newsletter'), ('welcome', 'Welcome Email'), ('file_share', 'File Share'), ('folder_share', 'Folder Share'), ('custom', 'Custom Email')], default='custom', max_length=50),
        ),
    ]
