# Generated by Django 4.2.23 on 2025-11-02 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0005_alter_emailtemplate_template_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingMailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name to identify this incoming mail configuration', max_length=100)),
                ('protocol', models.CharField(choices=[('imap', 'IMAP'), ('pop3', 'POP3')], default='imap', help_text='Mail protocol (IMAP or POP3)', max_length=10)),
                ('email_address', models.EmailField(help_text='Email address to fetch mail from', max_length=254)),
                ('mail_server', models.CharField(help_text='Mail server address (e.g., imap.gmail.com, imap.endevops.com)', max_length=255)),
                ('mail_port', models.PositiveIntegerField(help_text='Mail server port (e.g., 993 for IMAP SSL, 143 for IMAP STARTTLS, 995 for POP3 SSL)')),
                ('username', models.CharField(help_text='Username for authentication (usually email address)', max_length=255)),
                ('password', models.CharField(help_text='Password or app password', max_length=255)),
                ('auth_method', models.CharField(choices=[('password', 'Normal Password'), ('oauth2', 'OAuth2')], default='password', help_text='Authentication method', max_length=20)),
                ('connection_security', models.CharField(choices=[('none', 'None'), ('ssl', 'SSL/TLS'), ('starttls', 'STARTTLS')], default='starttls', help_text='Connection security method', max_length=20)),
                ('auto_fetch', models.BooleanField(default=True, help_text='Automatically fetch new messages')),
                ('fetch_interval', models.PositiveIntegerField(default=10, help_text='Fetch interval in minutes')),
                ('fetch_on_startup', models.BooleanField(default=True, help_text='Check for new messages at startup')),
                ('inbox_folder', models.CharField(default='INBOX', help_text='IMAP folder to fetch from', max_length=100)),
                ('trash_folder', models.CharField(blank=True, default='Trash', help_text='Trash folder name', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('last_fetched', models.DateTimeField(blank=True, help_text='Last time emails were fetched', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Incoming Mail Config',
                'verbose_name_plural': 'Incoming Mail Configs',
            },
        ),
        migrations.AddField(
            model_name='emailinbox',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this inbox', null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='message_id',
            field=models.CharField(blank=True, help_text='Unique message ID from email server', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='raw_content',
            field=models.TextField(blank=True, help_text='Raw email content', null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='uid',
            field=models.CharField(blank=True, help_text='UID from IMAP server', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emailinbox',
            name='configuration',
            field=models.ForeignKey(help_text='SMTP configuration for sending emails', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_inboxes', to='email_manager.emailconfiguration'),
        ),
        migrations.AddField(
            model_name='emailinbox',
            name='incoming_config',
            field=models.ForeignKey(blank=True, help_text='IMAP/POP3 configuration for receiving emails', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inboxes', to='email_manager.incomingmailconfiguration'),
        ),
    ]
