# Generated by Django 5.2.7 on 2025-10-10 17:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyWebhookSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('sync_all', 'Sync All Subscriptions'), ('create', 'Create Subscription'), ('update', 'Update Subscription'), ('delete', 'Delete Subscription')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('subscriptions_synced', models.IntegerField(default=0)),
                ('subscriptions_created', models.IntegerField(default=0)),
                ('subscriptions_updated', models.IntegerField(default=0)),
                ('subscriptions_deleted', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=255)),
            ],
            options={
                'verbose_name': 'Webhook Sync Log',
                'verbose_name_plural': 'Webhook Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopifyWebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(max_length=255, unique=True)),
                ('legacy_resource_id', models.BigIntegerField(blank=True, null=True)),
                ('topic', models.CharField(choices=[('orders/create', 'Orders Create'), ('orders/updated', 'Orders Updated'), ('orders/cancelled', 'Orders Cancelled'), ('orders/fulfilled', 'Orders Fulfilled'), ('orders/paid', 'Orders Paid'), ('orders/partially_fulfilled', 'Orders Partially Fulfilled'), ('orders/delete', 'Orders Delete'), ('products/create', 'Products Create'), ('products/update', 'Products Update'), ('products/delete', 'Products Delete'), ('customers/create', 'Customers Create'), ('customers/update', 'Customers Update'), ('customers/delete', 'Customers Delete'), ('customers/enable', 'Customers Enable'), ('customers/disable', 'Customers Disable'), ('inventory_items/create', 'Inventory Items Create'), ('inventory_items/update', 'Inventory Items Update'), ('inventory_items/delete', 'Inventory Items Delete'), ('inventory_levels/connect', 'Inventory Levels Connect'), ('inventory_levels/update', 'Inventory Levels Update'), ('inventory_levels/disconnect', 'Inventory Levels Disconnect'), ('fulfillments/create', 'Fulfillments Create'), ('fulfillments/update', 'Fulfillments Update'), ('refunds/create', 'Refunds Create'), ('collections/create', 'Collections Create'), ('collections/update', 'Collections Update'), ('collections/delete', 'Collections Delete'), ('app/uninstalled', 'App Uninstalled'), ('shop/update', 'Shop Update'), ('checkouts/create', 'Checkouts Create'), ('checkouts/update', 'Checkouts Update'), ('checkouts/delete', 'Checkouts Delete'), ('disputes/create', 'Disputes Create'), ('disputes/update', 'Disputes Update'), ('other', 'Other')], max_length=100)),
                ('format', models.CharField(choices=[('json', 'JSON'), ('xml', 'XML')], default='json', max_length=10)),
                ('endpoint_type', models.CharField(choices=[('http', 'HTTP/HTTPS'), ('eventbridge', 'Amazon EventBridge'), ('pubsub', 'Google Cloud Pub/Sub')], default='http', max_length=20)),
                ('uri', models.URLField(help_text='Webhook destination URL', max_length=500)),
                ('api_version', models.CharField(blank=True, help_text='Admin API version', max_length=20)),
                ('filter_query', models.TextField(blank=True, help_text='Search syntax filter for webhook events')),
                ('include_fields', models.JSONField(blank=True, default=list, help_text='List of fields to include in payload')),
                ('metafield_namespaces', models.JSONField(blank=True, default=list, help_text='Metafield namespaces to include')),
                ('is_active', models.BooleanField(default=True)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webhook Subscription',
                'verbose_name_plural': 'Webhook Subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['topic', 'is_active'], name='subscriptio_topic_b202e4_idx'), models.Index(fields=['endpoint_type'], name='subscriptio_endpoin_13cb68_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopifyWebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='subscriptions.shopifywebhooksubscription')),
            ],
            options={
                'verbose_name': 'Webhook Delivery',
                'verbose_name_plural': 'Webhook Deliveries',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['status', 'attempted_at'], name='subscriptio_status_6b51ef_idx'), models.Index(fields=['subscription', 'status'], name='subscriptio_subscri_fd25be_idx')],
            },
        ),
    ]
