# Generated by Django 5.2.7 on 2025-10-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifywebhooksubscription',
            name='api_version',
            field=models.CharField(blank=True, default='', help_text='Admin API version', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopifywebhooksubscription',
            name='filter_query',
            field=models.TextField(blank=True, default='', help_text='Search syntax filter for webhook events'),
        ),
    ]
