# Generated by Django 5.2.7 on 2025-10-10 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('bulk_import', 'Bulk Import'), ('single_update', 'Single Update'), ('webhook_update', 'Webhook Update')], max_length=20)),
                ('customers_processed', models.IntegerField(default=0)),
                ('customers_created', models.IntegerField(default=0)),
                ('customers_updated', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopifyCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(help_text='Shopify Global ID', max_length=100, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(choices=[('ENABLED', 'Enabled'), ('DISABLED', 'Disabled')], default='ENABLED', max_length=20)),
                ('verified_email', models.BooleanField(default=False)),
                ('tax_exempt', models.BooleanField(default=False)),
                ('number_of_orders', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Customer tags as JSON array')),
                ('accepts_marketing', models.BooleanField(default=False)),
                ('marketing_opt_in_level', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending Sync'), ('error', 'Sync Error')], default='synced', max_length=20)),
                ('local_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopifyCustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(help_text='Shopify Address ID', max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('address1', models.CharField(blank=True, max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('province_code', models.CharField(blank=True, max_length=10)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('country_name', models.CharField(blank=True, max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('store_domain', models.CharField(default='7fa66c-ac.myshopify.com', max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.shopifycustomer')),
            ],
            options={
                'ordering': ['-is_default', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='shopifycustomer',
            index=models.Index(fields=['email'], name='customers_s_email_1656b7_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifycustomer',
            index=models.Index(fields=['shopify_id'], name='customers_s_shopify_fd5251_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifycustomer',
            index=models.Index(fields=['state'], name='customers_s_state_9dfcfa_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifycustomer',
            index=models.Index(fields=['store_domain'], name='customers_s_store_d_2dd6bb_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifycustomeraddress',
            index=models.Index(fields=['customer', 'is_default'], name='customers_s_custome_5c8471_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifycustomeraddress',
            index=models.Index(fields=['country_code'], name='customers_s_country_f16add_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifycustomeraddress',
            index=models.Index(fields=['province_code'], name='customers_s_provinc_b63f8b_idx'),
        ),
    ]
