# Generated by Django 4.2.23 on 2025-12-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_shopifycustomeraddress_last_pushed_to_shopify_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifycustomer',
            name='last_pushed_to_shopify',
            field=models.DateTimeField(blank=True, help_text='Last successful push to Shopify', null=True),
        ),
        migrations.AddField(
            model_name='shopifycustomer',
            name='needs_shopify_push',
            field=models.BooleanField(default=False, help_text='True if customer needs to be pushed to Shopify'),
        ),
        migrations.AddField(
            model_name='shopifycustomer',
            name='shopify_push_error',
            field=models.TextField(blank=True, help_text='Last error message from Shopify push'),
        ),
        migrations.AddIndex(
            model_name='shopifycustomer',
            index=models.Index(fields=['needs_shopify_push'], name='customers_s_needs_s_af3171_idx'),
        ),
    ]
