# Generated by Django 4.2.23 on 2025-12-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_shopifycustomer_last_pushed_to_shopify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifycustomer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shopifycustomer',
            name='shopify_id',
            field=models.CharField(blank=True, help_text='Shopify Global ID', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shopifycustomer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shopifycustomeraddress',
            name='shopify_id',
            field=models.CharField(blank=True, help_text='Shopify Address ID', max_length=100, null=True, unique=True),
        ),
    ]
