# Generated by Django 4.2.23 on 2025-12-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_shopifycustomer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifycustomer',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone in E.164 format (e.g., +61400000000)', max_length=20),
        ),
    ]
